"""Test with real Next.js project structure."""

import pytest
from pathlib import Path
import tempfile
import shutil
from palace.core.hippocampus import Hippocampus
from palace.ingest.pipeline import BigBangPipeline
from palace.ingest.parsers.nextjs import NextJSEnhancer


class TestNextJSRealWorld:
    """Tests with real Next.js project structure."""

    @pytest.fixture
    def nextjs_repo(self):
        """Create a temporary Next.js repository."""
        repo_dir = tempfile.mkdtemp(prefix="nextjs_test_")
        repo_path = Path(repo_dir)

        # Create Next.js config
        (repo_path / "next.config.js").write_text("""
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};
module.exports = nextConfig;
""")

        # Create package.json
        (repo_path / "package.json").write_text("""
{
  "name": "test-nextjs-app",
  "version": "0.1.0",
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.0.0"
  }
}
""")

        # Create app directory structure
        app_dir = repo_path / "app"
        app_dir.mkdir()

        # Create root layout
        (app_dir / "layout.tsx").write_text("""
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
""")

        # Create home page
        (app_dir / "page.tsx").write_text("""
import Image from 'next/image'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col">
      <div className="z-10 max-w-5xl w-full items-center">
        <h1 className="text-2xl font-bold">Test App</h1>
      </div>
    </main>
  )
}
""")

        # Create API route
        api_dir = app_dir / "api" / "users"
        api_dir.mkdir(parents=True)
        (api_dir / "route.ts").write_text("""
import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json({ users: [] })
}
""")

        # Create dashboard group
        dashboard_dir = app_dir / "dashboard"
        dashboard_dir.mkdir()
        (dashboard_dir / "page.tsx").write_text("""
export default function DashboardPage() {
  return (
    <div>
      <h1>Dashboard</h1>
      <p>Welcome to your dashboard</p>
    </div>
  )
}
""")

        # Create components directory
        components_dir = repo_path / "components"
        components_dir.mkdir()
        (components_dir / "Header.tsx").write_text("""
export default function Header() {
  return (
    <header className="border-b">
      <nav className="flex">
        <a href="/">Home</a>
        <a href="/dashboard">Dashboard</a>
      </nav>
    </header>
  )
}
""")

        yield repo_path

        # Cleanup
        if Path(repo_dir).exists():
            shutil.rmtree(repo_dir)

    @pytest.fixture
    def hippocampus(self, nextjs_repo):
        """Create test hippocampus instance."""
        palace_dir = nextjs_repo / ".palace"
        palace_dir.mkdir(parents=True, exist_ok=True)

        hippo = Hippocampus(str(palace_dir))
        hippo.initialize_schema()
        yield hippo
        hippo.close()

    @pytest.fixture
    def pipeline(self, hippocampus):
        """Create test pipeline."""
        return BigBangPipeline(hippocampus, concept_extractor=None)

    def test_nextjs_detection(self, nextjs_repo):
        """Test Next.js project detection."""
        enhancer = NextJSEnhancer(nextjs_repo)

        assert enhancer.is_nextjs_project()

    def test_router_detection_app_router(self, nextjs_repo):
        """Test App Router detection."""
        enhancer = NextJSEnhancer(nextjs_repo)

        router_type = enhancer.get_router_type()
        assert router_type == "app"

    def test_route_extraction_app_router(self, nextjs_repo):
        """Test route extraction from App Router."""
        enhancer = NextJSEnhancer(nextjs_repo)
        routes = enhancer.extract_routes()

        # Should have app routes
        assert len(routes["app"]) > 0

        # Check for specific routes
        route_paths = [r["path"] for r in routes["app"]]
        assert "/" in route_paths  # Root page
        assert "/dashboard" in route_paths  # Dashboard page

        # Should have API routes
        assert len(routes["api"]) > 0
        api_paths = [r["path"] for r in routes["api"]]
        assert any("/api" in path for path in api_paths)

    def test_ingest_nextjs_project(self, nextjs_repo, pipeline):
        """Test ingesting entire Next.js project."""
        # Find all TypeScript/JavaScript files
        files = list(nextjs_repo.rglob("*.ts")) + list(nextjs_repo.rglob("*.tsx")) + list(nextjs_repo.rglob("*.js"))

        results = {"success": 0, "skipped": 0, "errors": 0}

        for file_path in files:
            if file_path.is_file() and "node_modules" not in str(file_path):
                result = pipeline.ingest_file(file_path)
                if result["status"] == "success":
                    results["success"] += 1
                elif result["status"] == "skipped":
                    results["skipped"] += 1
                else:
                    results["errors"] += 1

        # Should ingest most files successfully
        assert results["success"] >= 3  # At least some files
        assert results["errors"] == 0  # No errors

    def test_framework_hints(self, nextjs_repo):
        """Test framework hint extraction."""
        enhancer = NextJSEnhancer(nextjs_repo)
        hints = enhancer.get_framework_hints()

        assert hints["framework"] == "nextjs"
        assert hints["router_type"] == "app"
        assert len(hints["routes"]["app"]) > 0


class TestTypeScriptReactMonorepo:
    """Tests with TypeScript monorepo structure."""

    @pytest.fixture
    def monorepo(self):
        """Create a temporary monorepo."""
        repo_dir = tempfile.mkdtemp(prefix="monorepo_test_")
        repo_path = Path(repo_dir)

        # Create package.json
        (repo_path / "package.json").write_text("""
{
  "name": "test-monorepo",
  "version": "0.1.0",
  "private": true,
  "workspaces": ["packages/*"]
}
""")

        # Create shared package
        shared_dir = repo_path / "packages" / "shared"
        shared_dir.mkdir(parents=True)
        (shared_dir / "package.json").write_text('{"name": "@test/shared", "version": "0.1.0"}')
        (shared_dir / "types.ts").write_text("""
export interface User {
  id: number;
  name: string;
  email: string;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
}

export type UserId = number;
export type UserName = string;
""")

        # Create API package
        api_dir = repo_path / "packages" / "api"
        api_dir.mkdir(parents=True)
        (api_dir / "package.json").write_text('{"name": "@test/api", "version": "0.1.0"}')
        (api_dir / "users.ts").write_text("""
import type { User } from '@test/shared';

export async function getUsers(): Promise<User[]> {
  const response = await fetch('/api/users');
  return response.json();
}

export async function getUserById(id: number): Promise<User | null> {
  const users = await getUsers();
  return users.find(u => u.id === id) || null;
}
""")

        # Create web package
        web_dir = repo_path / "packages" / "web"
        web_dir.mkdir(parents=True)
        (web_dir / "package.json").write_text('{"name": "@test/web", "version": "0.1.0"}')
        (web_dir / "components" / "UserList.tsx").write_text("""
import type { User } from '@test/shared';
import { getUsers } from '@test/api';

export function UserList() {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    getUsers().then(setUsers);
  }, []);

  return (
    <ul>
      {users.map(user => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
}
""")

        yield repo_path

        # Cleanup
        if Path(repo_dir).exists():
            shutil.rmtree(repo_dir)

    @pytest.fixture
    def hippocampus(self, monorepo):
        """Create test hippocampus instance."""
        palace_dir = monorepo / ".palace"
        palace_dir.mkdir(parents=True, exist_ok=True)

        hippo = Hippocampus(str(palace_dir))
        hippo.initialize_schema()
        yield hippo
        hippo.close()

    @pytest.fixture
    def pipeline(self, hippocampus):
        """Create test pipeline."""
        return BigBangPipeline(hippocampus, concept_extractor=None)

    def test_ingest_monorepo(self, monorepo, pipeline):
        """Test ingesting monorepo."""
        # Find all TypeScript files
        files = list(monorepo.rglob("*.ts")) + list(monorepo.rglob("*.tsx"))

        results = {"success": 0, "skipped": 0, "errors": 0}

        for file_path in files:
            if file_path.is_file():
                result = pipeline.ingest_file(file_path)
                if result["status"] == "success":
                    results["success"] += 1
                elif result["status"] == "skipped":
                    results["skipped"] += 1
                else:
                    results["errors"] += 1

        # Should ingest all TS files
        assert results["success"] >= 3
        assert results["errors"] == 0

    def test_cross_package_dependencies(self, monorepo, pipeline):
        """Test that cross-package dependencies are extracted."""
        shared_types = monorepo / "packages" / "shared" / "types.ts"
        result = pipeline.ingest_file(shared_types)

        assert result["status"] == "success"
        # Should extract the User interface and ApiResponse interface
        assert result["symbols"] >= 2

        # API file imports from shared
        api_users = monorepo / "packages" / "api" / "users.ts"
        result = pipeline.ingest_file(api_users)

        assert result["status"] == "success"
        # Should have dependencies
        assert result["dependencies"] > 0
